const ALL_TRUE = {
  canViewStudents: true,
  canManageStudents: true,
  canViewAttendance: true,
  canManageAttendance: true,
  canViewFeedback: true,
  canManageFeedback: true,
  canViewPayments: true,
  canManagePayments: true,
  canViewRevenue: true,
  canManageRevenue: true,
  canViewScheduler: true,
  canManageScheduler: true,
  canViewTimetable: true,
  canManageTimetable: true,
  canViewExams: true,
  canManageExams: true,
  canManageSettings: true,
  canManageHomework: true,
  canManageVideoLessons: true,
  canViewWallet: true,
  canManageWallet: true,
};

const DEFAULT_ROLE_PERMISSIONS = {
  admin: { ...ALL_TRUE },
  teacher: {
    canViewStudents: true,
    canManageStudents: false,
    canViewAttendance: true,
    canManageAttendance: true,
    canViewFeedback: true,
    canManageFeedback: true,
    canViewPayments: false,
    canManagePayments: false,
    canViewRevenue: false,
    canManageRevenue: false,
    canViewScheduler: true,
    canManageScheduler: false,
    canViewTimetable: true,
    canManageTimetable: false,
    canViewExams: true,
    canManageExams: false,
    canManageSettings: false,
    canManageHomework: false,
    canManageVideoLessons: false,
    canViewWallet: false,
    canManageWallet: false,
  },
  sales: {
    canViewStudents: true,
    canManageStudents: true,
    canViewAttendance: false,
    canManageAttendance: false,
    canViewFeedback: false,
    canManageFeedback: false,
    canViewPayments: true,
    canManagePayments: true,
    canViewRevenue: true,
    canManageRevenue: false,
    canViewScheduler: false,
    canManageScheduler: false,
    canViewTimetable: false,
    canManageTimetable: false,
    canViewExams: false,
    canManageExams: false,
    canManageSettings: false,
    canManageHomework: false,
    canManageVideoLessons: false,
    canViewWallet: false,
    canManageWallet: false,
  },
  receptionist: {
    canViewStudents: true,
    canManageStudents: false,
    canViewAttendance: true,
    canManageAttendance: false,
    canViewFeedback: false,
    canManageFeedback: false,
    canViewPayments: true,
    canManagePayments: false,
    canViewRevenue: false,
    canManageRevenue: false,
    canViewScheduler: true,
    canManageScheduler: false,
    canViewTimetable: true,
    canManageTimetable: false,
    canViewExams: false,
    canManageExams: false,
    canManageSettings: false,
    canManageHomework: false,
    canManageVideoLessons: false,
    canViewWallet: false,
    canManageWallet: false,
  },
  manager: {
    canViewStudents: true,
    canManageStudents: true,
    canViewAttendance: true,
    canManageAttendance: true,
    canViewFeedback: true,
    canManageFeedback: true,
    canViewPayments: true,
    canManagePayments: false,
    canViewRevenue: true,
    canManageRevenue: false,
    canViewScheduler: true,
    canManageScheduler: true,
    canViewTimetable: true,
    canManageTimetable: true,
    canViewExams: true,
    canManageExams: true,
    canManageSettings: false,
    canManageHomework: false,
    canManageVideoLessons: false,
    canViewWallet: true,
    canManageWallet: false,
  },
};

module.exports = { DEFAULT_ROLE_PERMISSIONS };
